/* Rust PaddleOCR C API */
/* This file is auto-generated by cbindgen */

/* Generated with cbindgen:0.24.5 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 默认边界尺寸常量
 * Default rectangle border size constant
 */
#define ROCR_Det_RECT_BORDER_SIZE 10

/**
 * OCR结果状态码
 */
typedef enum ROCR_RocrStatus {
    ROCR_RocrStatus_Success = 0,
    ROCR_RocrStatus_InitError = 1,
    ROCR_RocrStatus_FileNotFound = 2,
    ROCR_RocrStatus_ImageLoadError = 3,
    ROCR_RocrStatus_ProcessError = 4,
    ROCR_RocrStatus_MemoryError = 5,
    ROCR_RocrStatus_InvalidParam = 6,
    ROCR_RocrStatus_NotInitialized = 7,
} ROCR_RocrStatus;

/**
 * OCR引擎句柄类型
 */
typedef size_t ROCR_RocrHandle;

/**
 * 文本框位置信息
 */
typedef struct ROCR_RocrTextBox {
    char *TEXT;
    float CONFIDENCE;
    int LEFT;
    int TOP;
    unsigned int WIDTH;
    unsigned int HEIGHT;
} ROCR_RocrTextBox;

/**
 * OCR结果
 */
typedef struct ROCR_RocrResult {
    enum ROCR_RocrStatus STATUS;
    size_t COUNT;
    struct ROCR_RocrTextBox *BOXES;
} ROCR_RocrResult;

/**
 * 简单文本结果
 */
typedef struct ROCR_RocrSimpleResult {
    enum ROCR_RocrStatus STATUS;
    size_t COUNT;
    char **TEXTS;
} ROCR_RocrSimpleResult;

/**
 * 初始化OCR引擎，返回引擎句柄
 */
ROCR_RocrHandle rocr_create_engine(const char *aDetModelPath,
                                   const char *aRecModelPath,
                                   const char *aKeysPath);

/**
 * 使用自定义配置创建OCR引擎，返回引擎句柄
 */
ROCR_RocrHandle rocr_create_engine_with_config(const char *aDetModelPath,
                                               const char *aRecModelPath,
                                               const char *aKeysPath,
                                               unsigned int aRectBorderSize,
                                               int aMergeBoxes,
                                               int aMergeThreshold);

/**
 * 使用字节数据创建OCR引擎，返回引擎句柄
 */
ROCR_RocrHandle rocr_create_engine_with_bytes(const uint8_t *aDetModelData,
                                              size_t aDetModelSize,
                                              const uint8_t *aRecModelData,
                                              size_t aRecModelSize,
                                              const uint8_t *aKeysData,
                                              size_t aKeysSize,
                                              unsigned int aRectBorderSize,
                                              int aMergeBoxes,
                                              int aMergeThreshold);

/**
 * 销毁OCR引擎实例
 */
enum ROCR_RocrStatus rocr_destroy_engine(ROCR_RocrHandle aHandle);

/**
 * 识别图像中的文本（详细模式）
 */
struct ROCR_RocrResult rocr_recognize_detailed(ROCR_RocrHandle aHandle,
                                               const char *aImagePath);

/**
 * 识别图像中的文本（简单模式）
 */
struct ROCR_RocrSimpleResult rocr_recognize_simple(ROCR_RocrHandle aHandle,
                                                   const char *aImagePath);

/**
 * 释放详细结果的内存
 */
void rocr_free_result(struct ROCR_RocrResult *aResult);

/**
 * 释放简单结果的内存
 */
void rocr_free_simple_result(struct ROCR_RocrSimpleResult *aResult);

/**
 * 释放所有OCR引擎资源
 */
void rocr_cleanup(void);

/**
 * 获取版本信息
 */
const char *rocr_version(void);
