name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # amd64架构 - 两个版本
          - os: ubuntu-latest
            artifact_name: ocr
            asset_name: ocr-v4-linux-amd64
            target: x86_64-unknown-linux-gnu
            features: ""
          - os: ubuntu-latest
            artifact_name: ocr
            asset_name: ocr-v5-linux-amd64
            target: x86_64-unknown-linux-gnu
            features: "--features v5"
          - os: windows-2022
            artifact_name: ocr.exe
            asset_name: ocr-v4-windows-amd64.exe
            target: x86_64-pc-windows-msvc
            features: ""
          - os: windows-2022
            artifact_name: ocr.exe
            asset_name: ocr-v5-windows-amd64.exe
            target: x86_64-pc-windows-msvc
            features: "--features v5"
          - os: macos-latest
            artifact_name: ocr
            asset_name: ocr-v4-macos-amd64
            target: x86_64-apple-darwin
            features: ""
          - os: macos-latest
            artifact_name: ocr
            asset_name: ocr-v5-macos-amd64
            target: x86_64-apple-darwin
            features: "--features v5"
          
          # arm64架构 - 两个版本
          - os: ubuntu-latest
            artifact_name: ocr
            asset_name: ocr-v4-linux-arm64
            target: aarch64-unknown-linux-gnu
            features: ""
          - os: ubuntu-latest
            artifact_name: ocr
            asset_name: ocr-v5-linux-arm64
            target: aarch64-unknown-linux-gnu
            features: "--features v5"
          - os: macos-latest
            artifact_name: ocr
            asset_name: ocr-v4-macos-arm64
            target: aarch64-apple-darwin
            features: ""
          - os: macos-latest
            artifact_name: ocr
            asset_name: ocr-v5-macos-arm64
            target: aarch64-apple-darwin
            features: "--features v5"
          
          # 32位架构 - 两个版本
          - os: windows-2022
            artifact_name: ocr.exe
            asset_name: ocr-v4-windows-x86.exe
            target: i686-pc-windows-msvc
            features: ""
          - os: windows-2022
            artifact_name: ocr.exe
            asset_name: ocr-v5-windows-x86.exe
            target: i686-pc-windows-msvc
            features: "--features v5"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      
      - name: Setup Windows Build Environment
        if: matrix.os == 'windows-2022'
        run: |
          echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" >> $GITHUB_ENV
        shell: bash
    
      - name: Install Cross-Compilation Dependencies
        if: contains(matrix.target, 'aarch64-unknown-linux-gnu')
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
        shell: bash
      
      - name: Set Cross-Compilation Environment Variables
        if: contains(matrix.target, 'aarch64-unknown-linux-gnu')
        run: |
          echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
          echo "AR_aarch64_unknown_linux_gnu=aarch64-linux-gnu-ar" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
        shell: bash
      
      - name: Build
        if: matrix.os != 'windows-2022'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --target ${{ matrix.target }} ${{ matrix.features }}
      
      - name: Run tests
        if: contains(matrix.target, 'x86_64') && matrix.os != 'windows-2022'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --target ${{ matrix.target }} ${{ matrix.features }}
      
      - name: Build Release Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin ocr --target ${{ matrix.target }} ${{ matrix.features }}

      - name: Rename Binary
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-2022" ]; then
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          else
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
          fi
      
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.asset_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ matrix.asset_name }}

